# Generated by Django 5.0 on 2023-12-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
