# Generated by Django 5.0 on 2023-12-29 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_booking_date_remove_booking_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dia',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 20, 28, 30, 740442)),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
